export default function BusinessPlan() {
  return (
    <div className="mb-5">
      <h2>Business Plan</h2>
      <div className="row mt-3">
        <div className="col-sm-12 col-md-4 text-center">
          <img src="/business-plan.svg" width="300px" height="auto" alt="" />
        </div>
        <div className="col-sm-12 col-md-8">
          <p>
            For a better flow of movement during an emergency is to create a
            huge network with each and every hospital in the country that are
            willing to connect with our database so as to allow a smooth
            functioning of the app. After which, users will be acquired through
            commercials, organic marketing, social media awareness etc. The
            guiding principle here is to grow the hospital base as much as
            possible, since we are not charging anything for the users the
            process of acquiring will be much easier in comparison to the
            business charging the consumer. The commission will be charged on
            the bill of the patient generated by the hospital whose request was
            accepted first so that it is fair for all the hospitals that charge
            higher for the some emergency procedures to the hospitals who charge
            less. In case of government hospitals, we do not charge anything so
            that quality treatment is available to each and every citizen in the
            country.
          </p>
        </div>
      </div>
    </div>
  );
}
